---
- hosts: web
  become: yes
  gather_facts: true
  tasks:
    - name: 'Instalaçao do pacotes webserver'
      become: yes
      apt:
        pkg:
          - php7.4
          - php-pear
          - php7.4-curl
          - php7.4-gd
          - php7.4-intl
          - php7.4-xmlrpc
          - php7.4-mysql
          - apache2
          - python3-mysqldb
          - wget
          - vim
          - zip
          - curl
        state: present
      when: ansible_os_family == 'Debian'