---
- hosts: db
  become: yes
  tasks:
    - name: 'Instalaçao do pacotes BD'
      apt:
        pkg:
          - mariadb-server
          - wget
          - zip
          - curl
          - vim
          - python3-mysqldb
        state: present
        update_cache: yes
    - name: 'criando db backup'
      mysql_db:
        name: backup
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
    - name: 'Criacao de usuario express mysql'
      community.mysql.mysql_user:
        host: '%'
        name: express
        password: 'AllSafe0!'
        priv: 'backup.*:ALL'
        state: present
        column_case_sensitive: false
        login_unix_socket: /run/mysqld/mysqld.sock
    - name: 'substituir bind do mysql'
      replace:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
      notify: RestartMysql     
  handlers:
    - name: RestartMysql
      service:
        name: mysql
        state: restarted
        enable: yes  